version: "3.8"

services:
  nodejs:
    build:
      context: .
      target: build
    command: [ "npm", "run", "debug" ]
    ports:
      - 8888:8080
      - 9229:9229
    volumes:
      - ./src:/usr/src/app/src
    env_file: .env
    networks:
      - local-dev

networks:
  local-dev:
    external: true
