version: "3.8"

services:
  nodejs:
    build:
      context: .
    command: [ "npm", "run", "debug" ]
    ports:
      - 8888:8080
      - 9229:9229
    volumes:
      - ./src:/usr/src/app/src

  minio:
    restart: always
    image: minio/minio:latest
    ports:
      - 9001:9000
    volumes:
      - s3_data:/data
    command: minio server /data

volumes:
  s3_data: null
