version: "3.8"

services:
  fileserver:
    build:
      context: .
      target: build
    image: fileserver
    command: [ "npm", "run", "debug" ]
    ports:
      - 8888:8080
      - 9229:9229
    volumes:
      - ./src:/usr/src/app/src
    env_file: .env
