version: "3.8"

services:
  fileserver:
    build:
      context: .
      target: build
    image: fileserver
    command: [ "npm", "run", "debug" ]
    ports:
      - 8889:8080
      - 9229:9229
    volumes:
      - ./src:/usr/src/app/src
    env_file: .env

  minio:
    restart: always
    image: minio/minio:RELEASE.2022-07-17T15-43-14Z.fips
    volumes:
      - s3_data:/data
    command: minio server /data

volumes:
  s3_data: null
